trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Scan_local_project
  steps:
  - task: trivy@1
    inputs:
      path: .
- job: Scan_ubuntu_image
  steps:
  - task: trivy@1
    inputs:
      image: ubuntu