trigger:
- master

resources:
- repo: self

variables:
  trivyVersion: 0.37.1
  tag: '$(Build.BuildNumber)'
  imageName: 'alienke/py-flask-tut'

stages:
- stage: Build
  displayName: Build, Scan and Push image
  jobs:  
  - job: Build
    displayName: Build, Scan and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'alienke_dockerHub'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/'
        tags: '$(tag)'

    - task: Docker@2
      inputs:
        containerRegistry: 'alienke_dockerHub'
        repository: '$(imageName)'
        command: 'push'
        tags: '$(tag)'          

    - task: trivy@1
      displayName: trivy Filesystem scan
      inputs:
        path: .

    - task: trivy@1
      displayName: trivy Image scan
      inputs:
        image: '$(imageName).$(tag)'